// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class McpServerConfig {
    "type"?: string;
    "command"?: string;
    "args"?: string[];
    "env"?: { [_ in string]?: string };
    "url"?: string;
    "headers"?: { [_ in string]?: string };

    /** Creates a new McpServerConfig instance. */
    constructor($$source: Partial<McpServerConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new McpServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): McpServerConfig {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField3_0($$parsedSource["env"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField5_0($$parsedSource["headers"]);
        }
        return new McpServerConfig($$parsedSource as Partial<McpServerConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
