// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

export class Annotations {
    "audience"?: Role[];
    "priority"?: number | null;
    "lastModified"?: string | null;

    /** Creates a new Annotations instance. */
    constructor($$source: Partial<Annotations> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Annotations instance from a string or object.
     */
    static createFrom($$source: any = {}): Annotations {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("audience" in $$parsedSource) {
            $$parsedSource["audience"] = $$createField0_0($$parsedSource["audience"]);
        }
        return new Annotations($$parsedSource as Partial<Annotations>);
    }
}

export class ContentBlock {
    "type": string;
    "text"?: string;
    "data"?: string;
    "mimeType"?: string;
    "uri"?: string | null;
    "name"?: string;
    "description"?: string | null;
    "size"?: number | null;
    "title"?: string | null;
    "resource"?: json$0.RawMessage;
    "annotations"?: Annotations | null;

    /** Creates a new ContentBlock instance. */
    constructor($$source: Partial<ContentBlock> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ContentBlock {
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField10_0($$parsedSource["annotations"]);
        }
        return new ContentBlock($$parsedSource as Partial<ContentBlock>);
    }
}

export class Cost {
    "amount": number;
    "currency": string;

    /** Creates a new Cost instance. */
    constructor($$source: Partial<Cost> = {}) {
        if (!("amount" in $$source)) {
            this["amount"] = 0;
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cost instance from a string or object.
     */
    static createFrom($$source: any = {}): Cost {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cost($$parsedSource as Partial<Cost>);
    }
}

export class CurrentModeUpdate {
    "currentModeId": SessionModeID;

    /** Creates a new CurrentModeUpdate instance. */
    constructor($$source: Partial<CurrentModeUpdate> = {}) {
        if (!("currentModeId" in $$source)) {
            this["currentModeId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentModeUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): CurrentModeUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CurrentModeUpdate($$parsedSource as Partial<CurrentModeUpdate>);
    }
}

export class Plan {
    "entries": PlanEntry[];

    /** Creates a new Plan instance. */
    constructor($$source: Partial<Plan> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     */
    static createFrom($$source: any = {}): Plan {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new Plan($$parsedSource as Partial<Plan>);
    }
}

export class PlanEntry {
    "content": string;
    "status": PlanEntryStatus;
    "priority": PlanEntryPriority;

    /** Creates a new PlanEntry instance. */
    constructor($$source: Partial<PlanEntry> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = PlanEntryStatus.$zero;
        }
        if (!("priority" in $$source)) {
            this["priority"] = PlanEntryPriority.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanEntry($$parsedSource as Partial<PlanEntry>);
    }
}

export enum PlanEntryPriority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanPriorityHigh = "high",
    PlanPriorityMedium = "medium",
    PlanPriorityLow = "low",
};

export enum PlanEntryStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlanPending = "pending",
    PlanInProgress = "in_progress",
    PlanCompleted = "completed",
};

export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleAssistant = "assistant",
    RoleUser = "user",
};

export type SessionModeID = string;

export class ToolCall {
    "toolCallId": ToolCallID;
    "title": string;
    "kind": ToolKind;
    "status": ToolCallStatus;
    "content": ToolCallContent[];
    "locations": ToolCallLocation[];
    "rawInput": json$0.RawMessage;
    "rawOutput": json$0.RawMessage;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ToolKind.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = ToolCallStatus.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("rawInput" in $$source)) {
            this["rawInput"] = null;
        }
        if (!("rawOutput" in $$source)) {
            this["rawOutput"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField4_0($$parsedSource["content"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField5_0($$parsedSource["locations"]);
        }
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

export class ToolCallContent {
    "type": string;
    "content"?: ContentBlock | null;
    "path"?: string;
    "oldText"?: string | null;
    "newText"?: string;
    "terminalId"?: string;

    /** Creates a new ToolCallContent instance. */
    constructor($$source: Partial<ToolCallContent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallContent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallContent {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        return new ToolCallContent($$parsedSource as Partial<ToolCallContent>);
    }
}

export type ToolCallID = string;

export class ToolCallLocation {
    "path": string;
    "line"?: number | null;

    /** Creates a new ToolCallLocation instance. */
    constructor($$source: Partial<ToolCallLocation> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallLocation instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallLocation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallLocation($$parsedSource as Partial<ToolCallLocation>);
    }
}

export enum ToolCallStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ToolCallPending = "pending",
    ToolCallInProgress = "in_progress",
    ToolCallCompleted = "completed",
    ToolCallFailed = "failed",
};

export enum ToolKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ToolKindRead = "read",
    ToolKindEdit = "edit",
    ToolKindDelete = "delete",
    ToolKindMove = "move",
    ToolKindSearch = "search",
    ToolKindExecute = "execute",
    ToolKindThink = "think",
    ToolKindFetch = "fetch",
    ToolKindSwitchMode = "switch_mode",
    ToolKindOther = "other",
};

export class UsageUpdate {
    "size": number;
    "used": number;
    "cost"?: Cost | null;

    /** Creates a new UsageUpdate instance. */
    constructor($$source: Partial<UsageUpdate> = {}) {
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("used" in $$source)) {
            this["used"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageUpdate {
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cost" in $$parsedSource) {
            $$parsedSource["cost"] = $$createField2_0($$parsedSource["cost"]);
        }
        return new UsageUpdate($$parsedSource as Partial<UsageUpdate>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Annotations.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = PlanEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ToolCallContent.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ToolCallLocation.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ContentBlock.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = Cost.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
