// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";

/**
 * ACPAgentConfig contains an externally callable ACP agent endpoint.
 */
export class ACPAgentConfig {
    "id": string;
    "name"?: string;
    "enabled"?: boolean | null;

    /**
     * builtin, stdio (default), http, or sse
     */
    "type"?: string;
    "command"?: string;
    "args"?: string[];
    "url"?: string;
    "headers"?: { [_ in string]?: string };

    /** Creates a new ACPAgentConfig instance. */
    constructor($$source: Partial<ACPAgentConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ACPAgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ACPAgentConfig {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField5_0($$parsedSource["args"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField7_0($$parsedSource["headers"]);
        }
        return new ACPAgentConfig($$parsedSource as Partial<ACPAgentConfig>);
    }
}

/**
 * Config is the root configuration structure.
 */
export class Config {
    "agents"?: ACPAgentConfig[];
    "profiles": { [_ in string]?: ProfileConfig | null };

    /**
     * Provider configurations
     */
    "providers": { [_ in string]?: ProviderConfig | null };
    "mcpServers"?: { [_ in string]?: McpServerConfig | null };
    "channels"?: { [_ in string]?: any };

    /**
     * ChannelsEnabled controls whether desktop should run the remote channel gateway.
     */
    "channelsEnabled"?: boolean | null;
    "tools"?: { [_ in string]?: json$0.RawMessage };
    "logging"?: LoggingConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("profiles" in $$source)) {
            this["profiles"] = {};
        }
        if (!("providers" in $$source)) {
            this["providers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        const $$createField6_0 = $$createType14;
        const $$createField7_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField0_0($$parsedSource["agents"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField2_0($$parsedSource["providers"]);
        }
        if ("mcpServers" in $$parsedSource) {
            $$parsedSource["mcpServers"] = $$createField3_0($$parsedSource["mcpServers"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField4_0($$parsedSource["channels"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField6_0($$parsedSource["tools"]);
        }
        if ("logging" in $$parsedSource) {
            $$parsedSource["logging"] = $$createField7_0($$parsedSource["logging"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * LoggingConfig contains logging configuration.
 */
export class LoggingConfig {
    "enabled"?: boolean;

    /**
     * debug, info, warn, error
     */
    "level"?: string;

    /**
     * log to stdout
     */
    "stdout"?: boolean;

    /**
     * log file path
     */
    "file"?: string;

    /** Creates a new LoggingConfig instance. */
    constructor($$source: Partial<LoggingConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoggingConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LoggingConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoggingConfig($$parsedSource as Partial<LoggingConfig>);
    }
}

export const McpServerConfig = mcp$0.McpServerConfig;
export type McpServerConfig = mcp$0.McpServerConfig;

/**
 * ProfileConfig contains miya-agents runtime defaults.
 */
export class ProfileConfig {
    /**
     * provider name, e.g. "openai"
     */
    "provider": string;

    /**
     * model name, e.g. "deepseek-chat"
     */
    "model"?: string;

    /**
     * defaults to ~/.miya/workspace
     */
    "workspace"?: string;

    /**
     * defaults to 8192
     */
    "maxTokens"?: number;

    /**
     * defaults to 0.95
     */
    "temperature"?: number;

    /**
     * defaults to 128000
     */
    "contextWindowTokens"?: number;

    /**
     * defaults to 0.9
     */
    "contextWarnRatio"?: number;

    /** Creates a new ProfileConfig instance. */
    constructor($$source: Partial<ProfileConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileConfig($$parsedSource as Partial<ProfileConfig>);
    }
}

/**
 * ProviderConfig contains API credentials for a providers.
 */
export class ProviderConfig {
    "apiKey": string;

    /**
     * optional custom base URL
     */
    "apiBase"?: string;

    /**
     * "openai" (default) or "anthropic"
     */
    "type"?: string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ACPAgentConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ProfileConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = ProviderConfig.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = mcp$0.McpServerConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = LoggingConfig.createFrom;
