// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as acp$0 from "../../../github.com/lsongdev/miya-agents/acp/models.js";

export class Block {
    "id": string;
    "type": string;
    "content"?: string;
    "data"?: string;
    "mime"?: string;
    "uri"?: string;
    "name"?: string;
    "size"?: number;
    "tool"?: acp$0.ToolCall | null;
    "plan"?: acp$0.Plan | null;
    "raw"?: json$0.RawMessage;

    /** Creates a new Block instance. */
    constructor($$source: Partial<Block> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Block instance from a string or object.
     */
    static createFrom($$source: any = {}): Block {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField8_0($$parsedSource["tool"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField9_0($$parsedSource["plan"]);
        }
        return new Block($$parsedSource as Partial<Block>);
    }
}

export class Conversation {
    "id": string;
    "acpSessionId": string;
    "runtimeId"?: string;
    "title"?: string;
    "cwd"?: string;
    "source": Source;
    "messages": Message[];
    "usage"?: acp$0.UsageUpdate | null;
    "mode"?: acp$0.CurrentModeUpdate | null;
    "updatedAt": string;
    "createdAt": string;

    /** Creates a new Conversation instance. */
    constructor($$source: Partial<Conversation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("acpSessionId" in $$source)) {
            this["acpSessionId"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = (new Source());
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     */
    static createFrom($$source: any = {}): Conversation {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField5_0($$parsedSource["source"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField6_0($$parsedSource["messages"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField7_0($$parsedSource["usage"]);
        }
        if ("mode" in $$parsedSource) {
            $$parsedSource["mode"] = $$createField8_0($$parsedSource["mode"]);
        }
        return new Conversation($$parsedSource as Partial<Conversation>);
    }
}

export class Message {
    "id": string;
    "conversationId": string;
    "role": string;
    "protocolMessageId"?: string;
    "blocks": Block[];
    "status": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField4_0($$parsedSource["blocks"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class Source {
    "type": string;
    "channel"?: string;
    "accountId"?: string;
    "threadId"?: string;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

// Private type creation functions
const $$createType0 = acp$0.ToolCall.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = acp$0.Plan.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Source.createFrom;
const $$createType5 = Message.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = acp$0.UsageUpdate.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = acp$0.CurrentModeUpdate.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = Block.createFrom;
const $$createType12 = $Create.Array($$createType11);
