// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$1 from "../github.com/lsongdev/miya-agents/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "./internal/agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as channels$0 from "./internal/channels/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as conversation$0 from "./internal/conversation/models.js";

export function CancelSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1661183533, sessionID);
}

export function ChannelsServiceStatus(): $CancellablePromise<channels$0.Status> {
    return $Call.ByID(674758246).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1620748453, sessionID);
}

export function ConnectAgent(command: string): $CancellablePromise<void> {
    return $Call.ByID(4208552986, command);
}

export function ConnectConfiguredAgent(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(1728265482, agentID);
}

export function CreateSession(cwd: string): $CancellablePromise<agent$0.Session | null> {
    return $Call.ByID(2952361431, cwd).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DefaultCwd(): $CancellablePromise<string> {
    return $Call.ByID(488386004);
}

export function DeleteSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3306942022, sessionID);
}

export function DisconnectAgent(): $CancellablePromise<void> {
    return $Call.ByID(2154738592);
}

export function FetchProviderModels(providerID: string): $CancellablePromise<string[]> {
    return $Call.ByID(58019244, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConversation(sessionID: string): $CancellablePromise<agent$0.Conversation | null> {
    return $Call.ByID(2657599328, sessionID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

export function InitializeAgent(name: string, version: string): $CancellablePromise<agent$0.AgentInfo | null> {
    return $Call.ByID(3251009104, name, version).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListAgentSessions(): $CancellablePromise<agent$0.Session[]> {
    return $Call.ByID(4152340815).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListSessions(): $CancellablePromise<agent$0.Session[]> {
    return $Call.ByID(827108744).then(($result: any) => {
        return $$createType8($result);
    });
}

export function LoadMiyaConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3087674083).then(($result: any) => {
        return $$createType10($result);
    });
}

export function LoadSession(sessionID: string, cwd: string): $CancellablePromise<void> {
    return $Call.ByID(2280082259, sessionID, cwd);
}

export function MiyaConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1892314592);
}

export function ReconnectAgent(): $CancellablePromise<void> {
    return $Call.ByID(4116464635);
}

export function SaveMiyaConfig(cfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(3939757270, cfg);
}

export function SendPrompt(sessionID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2648413661, sessionID, message);
}

export function StartChannelsService(): $CancellablePromise<channels$0.Status> {
    return $Call.ByID(3313795346).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartWeChatLogin(rawConfig: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1172800822, rawConfig);
}

export function StopChannelsService(): $CancellablePromise<channels$0.Status> {
    return $Call.ByID(1321852108).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = channels$0.Status.createFrom;
const $$createType1 = agent$0.Session.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = conversation$0.Conversation.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = agent$0.AgentInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType1);
const $$createType9 = config$1.Config.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
