// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AttachmentData {
    "name": string;
    "mimeType": string;
    "size": number;
    "data": string;

    /** Creates a new AttachmentData instance. */
    constructor($$source: Partial<AttachmentData> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentData instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentData($$parsedSource as Partial<AttachmentData>);
    }
}

export class SkillInfo {
    "name": string;
    "description"?: string;
    "path": string;
    "prompt"?: string;

    /** Creates a new SkillInfo instance. */
    constructor($$source: Partial<SkillInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo($$parsedSource as Partial<SkillInfo>);
    }
}

export class UpdateCheckResult {
    "status": string;
    "message": string;
    "currentVersion": string;
    "state": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}
