// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../github.com/lsongdev/miya-agents/mcp/models.js";

export class AttachmentData {
    "name": string;
    "mimeType": string;
    "size": number;
    "data": string;

    /** Creates a new AttachmentData instance. */
    constructor($$source: Partial<AttachmentData> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentData instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentData($$parsedSource as Partial<AttachmentData>);
    }
}

export class MCPRegistryServerInfo {
    "id": string;
    "name": string;
    "description"?: string;
    "version"?: string;
    "installLabel": string;
    "requiredInputs"?: string[];
    "config": mcp$0.McpServerConfig | null;

    /** Creates a new MCPRegistryServerInfo instance. */
    constructor($$source: Partial<MCPRegistryServerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("installLabel" in $$source)) {
            this["installLabel"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPRegistryServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPRegistryServerInfo {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requiredInputs" in $$parsedSource) {
            $$parsedSource["requiredInputs"] = $$createField5_0($$parsedSource["requiredInputs"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField6_0($$parsedSource["config"]);
        }
        return new MCPRegistryServerInfo($$parsedSource as Partial<MCPRegistryServerInfo>);
    }
}

export class RegistrySkillInfo {
    "id": string;
    "name": string;
    "description"?: string;
    "source"?: string;
    "registry": string;
    "version"?: string;
    "installed": boolean;

    /** Creates a new RegistrySkillInfo instance. */
    constructor($$source: Partial<RegistrySkillInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("registry" in $$source)) {
            this["registry"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistrySkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistrySkillInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistrySkillInfo($$parsedSource as Partial<RegistrySkillInfo>);
    }
}

export class SkillInfo {
    "name": string;
    "description"?: string;
    "path": string;
    "prompt"?: string;

    /** Creates a new SkillInfo instance. */
    constructor($$source: Partial<SkillInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo($$parsedSource as Partial<SkillInfo>);
    }
}

export class UpdateCheckResult {
    "status": string;
    "message": string;
    "currentVersion": string;
    "state": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = mcp$0.McpServerConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
