// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {conversation} from '../models';

export function CancelSession(arg1:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectAgent(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<agent.Session>;

export function DefaultCwd():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function DisconnectAgent():Promise<void>;

export function GetConversation(arg1:string):Promise<conversation.Conversation>;

export function Greet(arg1:string):Promise<string>;

export function InitializeAgent(arg1:string,arg2:string):Promise<agent.AgentInfo>;

export function ListSessions():Promise<Array<agent.Session>>;

export function LoadSession(arg1:string,arg2:string):Promise<void>;

export function ReconnectAgent():Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;
