// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectAgent(arg1) {
  return window['go']['main']['App']['ConnectAgent'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DefaultCwd() {
  return window['go']['main']['App']['DefaultCwd']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisconnectAgent() {
  return window['go']['main']['App']['DisconnectAgent']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitializeAgent(arg1, arg2) {
  return window['go']['main']['App']['InitializeAgent'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadMiyaConfig() {
  return window['go']['main']['App']['LoadMiyaConfig']();
}

export function LoadSession(arg1, arg2) {
  return window['go']['main']['App']['LoadSession'](arg1, arg2);
}

export function MiyaConfigPath() {
  return window['go']['main']['App']['MiyaConfigPath']();
}

export function ReconnectAgent() {
  return window['go']['main']['App']['ReconnectAgent']();
}

export function SaveMiyaConfig(arg1) {
  return window['go']['main']['App']['SaveMiyaConfig'](arg1);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}
