// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {channels} from '../models';
import {agent} from '../models';
import {conversation} from '../models';
import {config} from '../models';

export function CancelSession(arg1:string):Promise<void>;

export function ChannelsServiceStatus():Promise<channels.Status>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectAgent(arg1:string):Promise<void>;

export function ConnectConfiguredAgent(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<agent.Session>;

export function DefaultCwd():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function DisconnectAgent():Promise<void>;

export function FetchProviderModels(arg1:string):Promise<Array<string>>;

export function GetConversation(arg1:string):Promise<conversation.Conversation>;

export function Greet(arg1:string):Promise<string>;

export function InitializeAgent(arg1:string,arg2:string):Promise<agent.AgentInfo>;

export function ListAgentSessions():Promise<Array<agent.Session>>;

export function ListSessions():Promise<Array<agent.Session>>;

export function LoadMiyaConfig():Promise<config.Config>;

export function LoadSession(arg1:string,arg2:string):Promise<void>;

export function MiyaConfigPath():Promise<string>;

export function ReconnectAgent():Promise<void>;

export function SaveMiyaConfig(arg1:config.Config):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function StartChannelsService():Promise<channels.Status>;

export function StopChannelsService():Promise<channels.Status>;
