// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as conversation$0 from "../conversation/models.js";

export class AgentInfo {
    "name": string;
    "version": string;
    "loadSession": boolean;

    /** Creates a new AgentInfo instance. */
    constructor($$source: Partial<AgentInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("loadSession" in $$source)) {
            this["loadSession"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentInfo($$parsedSource as Partial<AgentInfo>);
    }
}

export const Conversation = conversation$0.Conversation;
export type Conversation = conversation$0.Conversation;

export class Session {
    "id": string;
    "key"?: string;
    "cwd": string;
    "title"?: string;
    "updatedAt"?: string;
    "agentId"?: string;
    "agentName"?: string;
    "agentCommand"?: string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}
